FROM postgres:13

RUN apt-get update 
RUN apt-get -y install wget build-essential make gcc python3 postgresql-plpython3-13 postgresql-server-dev-13 libhiredis-dev

RUN wget https://github.com/zcaudate/redis_wrapper/archive/refs/tags/0.1.0.tar.gz && tar -xf 0.1.0.tar.gz
RUN cd redis_wrapper-0.1.0 && make && make install

RUN  apt-get clean && \
     rm -rf /var/cache/apt/* /var/lib/apt/lists/*

ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 5432
CMD ["postgres"]
