FROM postgres:13
ENV REDIS_WRAPPER_VERSION=0.1.0
WORKDIR /build


RUN apt-get update
RUN apt-get -y install wget build-essential make gcc python3 postgresql-plpython3-13 postgresql-server-dev-13 libhiredis-dev

RUN wget https://github.com/zcaudate/redis_wrapper/archive/refs/tags/0.1.0.tar.gz && tar -xf 0.1.0.tar.gz
RUN cd redis_wrapper-0.1.0 && make

FROM postgres:13
WORKDIR /build

COPY --from=builder /build ./
RUN make install

ENTRYPOINT ["/docker-entrypoint.sh"]
EXPOSE 5432
CMD ["postgres"]