FROM postgres:13
ENV REDIS_WRAPPER_VERSION=0.1.0
WORKDIR /build


RUN apt-get update
RUN apt-get -y install wget build-essential make gcc python3 postgresql-plpython3-13 postgresql-server-dev-13 libhiredis-dev

RUN wget https://github.com/zcaudate/redis_wrapper/archive/refs/tags/${REDIS_WRAPPER_VERSION}.tar.gz && tar -xf ${REDIS_WRAPPER_VERSION}.tar.gz
RUN cd redis_wrapper-${REDIS_WRAPPER_VERSION} && make && make install
