FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
ENV OPENRESTY_VERSION=1.21.4.1
ENV LUAROCKS_VERSION=3.9.1
ENV NCHAN_VERSION=1.3.0
WORKDIR /build
ENV PATH="/opt/openresty/bin:/opt/openresty/luajit/bin:${PATH}"

RUN apt-get update \
  && apt-get install -yqq wget git make gcc unzip build-essential \
        libreadline-dev zlib1g-dev libssl-dev libpcre3 libpcre3-dev \
        libhiredis-dev libsqlite3-dev libjemalloc-dev gettext-base \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# BUILD OPENRESTY                                                                                                                                                                                 
RUN wget https://openresty.org/download/openresty-${OPENRESTY_VERSION}.tar.gz && tar -xf openresty-${OPENRESTY_VERSION}.tar.gz
RUN wget https://github.com/slact/nchan/archive/refs/tags/v${NCHAN_VERSION}.tar.gz && tar -xf v${NCHAN_VERSION}.tar.gz
RUN wget https://luarocks.github.io/luarocks/releases/luarocks-${LUAROCKS_VERSION}.tar.gz && tar -xf luarocks-${LUAROCKS_VERSION}.tar.gz
RUN cd openresty-${OPENRESTY_VERSION} && ./configure --add-module=../nchan-${NCHAN_VERSION} --with-pcre-jit \
        --with-ipv6 --prefix=/opt/openresty \
        && make && make install
RUN cd luarocks-${LUAROCKS_VERSION} && ./configure --prefix=/opt/openresty/luajit --with-lua=/opt/openresty/luajit \
        --lua-suffix=jit --with-lua-include=/opt/openresty/luajit/include/luajit-2.1 \
        && make && make install

RUN /opt/openresty/luajit/bin/luarocks install lustache
RUN /opt/openresty/luajit/bin/luarocks install lua-cjson
RUN /opt/openresty/luajit/bin/luarocks install lua-resty-openssl
RUN /opt/openresty/luajit/bin/luarocks install lua-resty-mail                                                                                                                                     
RUN /opt/openresty/luajit/bin/luarocks install lua-resty-http
RUN /opt/openresty/luajit/bin/luarocks install lua-resty-uuid
RUN /opt/openresty/luajit/bin/luarocks install lua-resty-acme
RUN /opt/openresty/luajit/bin/luarocks install lsqlite3
RUN /opt/openresty/luajit/bin/luarocks install pgmoon

EXPOSE 80
CMD ["nginx"]
