FROM ubuntu:20.04
ENV DEBIAN_FRONTEND=noninteractive
ENV REDIS_VERSION=6.2.1
ENV LUAJIT_VERSION=2.1.1
ENV PATH="/opt/redis/bin:${PATH}"
WORKDIR /build

RUN apt-get update
RUN apt-get install -yqq wget git make gcc build-essential \
        libreadline-dev zlib1g-dev libssl-dev libpcre3 libpcre3-dev

RUN wget https://github.com/zcaudate/redis-luajit/archive/refs/tags/v${REDIS_VERSION}-luajit.tar.gz && tar -xf v${REDIS_VERSION}-luajit.tar.gz
RUN wget https://github.com/zcaudate/LuaJIT/archive/refs/tags/${LUAJIT_VERSION}-redis.tar.gz && tar -xf ${LUAJIT_VERSION}-redis.tar.gz
RUN rm -R redis-luajit-${REDIS_VERSION}-luajit/deps/LuaJIT
RUN mv LuaJIT-${LUAJIT_VERSION}-redis redis-luajit-${REDIS_VERSION}-luajit/deps/LuaJIT
RUN cd redis-luajit-${REDIS_VERSION}-luajit && make && make PREFIX=/opt/redis install
RUN cd redis-luajit-${REDIS_VERSION}-luajit/deps/LuaJIT && make install
RUN mv /usr/local/bin/luajit-2.1.0-beta3 /usr/local/bin/luajit

EXPOSE 6379
CMD ["redis-server", "--bind", "0.0.0.0"]
